Resources:
  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Events
      AttributeDefinitions:
        - AttributeName: "eventId"
          AttributeType: "S"
        - AttributeName: "orderDate"
          AttributeType: "S"
        - AttributeName: "status"
          AttributeType: "S"
        - AttributeName: "customerName"
          AttributeType: "S"
        - AttributeName: "customerEmail"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "eventId"
          KeyType: "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: "PAY_PER_REQUEST"